apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: apicurio-oauth
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '3.1'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - authentication:
          type: tls
        name: tls
        port: 9093
        tls: true
        type: internal
    replicas: 3
    storage:
      type: ephemeral
    version: 3.1.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  listeners:
    - addresses:
        - host: kafka-cluster-kafka-bootstrap.apicurio-oauth.svc
          port: 9093
      bootstrapServers: 'kafka-cluster-kafka-bootstrap.apicurio-oauth.svc:9093'
      name: tls
      type: tls
  observedGeneration: 1