apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-registry
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"apicurioregistry-kafkasql-ingress-6gxxh"}}'
